# Generated by Django 3.1.7 on 2023-08-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_auto_20230827_0858'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
