# Generated by Django 3.1.7 on 2023-08-26 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_auto_20230826_1039'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
    ]
