# Generated by Django 3.1.7 on 2023-08-26 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='team',
        ),
    ]
